
- name: Create folder directory for web configuration
  file:
    path: "{{ item }}"
    state: directory
    owner: splunk
    group: splunk
    recurse: yes
  with_items:
    - /opt/splunk/etc/apps/web_app/local/
    - /opt/splunk/etc/apps/web_app/appserver/
    - /opt/splunk/etc/apps/web_app/appserver/static
    - /opt/splunk/etc/apps/web_app/appserver/static/logincustombg
    
- name: copy server.conf to splunk server
  copy:
    src: ransomware.png
    dest: /opt/splunk/etc/apps/web_app/appserver/static/logincustombg/ransomware.png
    owner: splunk
    group: splunk
    
- name: copy web.conf to splunk server
  copy:
    src: web.conf
    dest: /opt/splunk/etc/apps/web_app/local/web.conf
    owner: splunk
    group: splunk
  notify: restart splunk
