- name: Run the equivalent of "apt-get update" as a separate step
  become: true
  apt:
    update_cache: yes
    
- name: Upgrade all packages to the latest version
  become: true
  apt:
    name: "*"
    state: latest

- name: Install required packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - build-essential
    - linux-headers-oem-20.04
    - net-tools
    - gdb
    - cmake
    - bison
    - flex
    - python3-pip
    - libffi-dev
    - libfuzzy-dev
    - automake
    - autoconf
    - libtool
    - libltdl-dev
    - p7zip-full
    - qbittorrent-nox

- name: Create stoq results directory
  become: true
  file:
    path: '/tmp/stoq_results'
    state: directory

- name: Create stoq inputs directory
  become: true
  file:
    path: '/tmp/stoq_inputs'
    state: directory

- name: Create stoq plugins directory
  become: true
  command: "mkdir -p /root/.stoq/plugins"

- name: Install Stoq
  become: true
  command: "pip3 install stoq-framework"

- name: Install Stoq filedir plugin
  become: true
  command: "stoq install --github stoq:filedir"

- name: Install Stoq peinfo plugin
  become: true
  command: "stoq install --github stoq:peinfo"

- name: Install Stoq yara plugin
  become: true
  command: "stoq install --github stoq:yara"

- name: Install Stoq hash plugin
  become: true
  command: "stoq install --github stoq:hash"

- name: Install Stoq stdout plugin
  become: true
  command: "stoq install --github stoq:stdout"

- name: Install Stoq
  become: true
  command: "sudo BUILD_LIB=1 stoq install --github stoq:hash_ssdeep"

- name: copy surge_dispatchers.yar dispatcher rule
  copy:
    src: surge_dispatchers.yar
    dest: /root/.stoq/plugins/yarascan/rules/surge_dispatchers.yar
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Change dispatch rules in yara rule
  become: true
  lineinfile:
    path: /root/.stoq/plugins/yarascan/yarascan.stoq
    line: 'dispatch_rules = rules/surge_dispatchers.yar'

- name: install startup script for stoq - systemd
  copy:
    src: systemd-stoq.service
    dest: /etc/systemd/system/stoq.service
    owner: root
    group: root
    mode: 0755
    force: yes

- name: systemctl daemon reload
  become: true
  command:  "systemctl daemon-reload"

- name: systemctl enable stoq
  become: true
  command:  "systemctl enable stoq.service"

- name: systemctl start stoq
  become: true
  command:  "systemctl start stoq.service"
