---
- name: Adding vars
  include_vars: file="../../../../users.yml"

- name: Adding surgers group
  become: true
  group:
    name: surgers
    state: present

- name: Adding Users
  become: true
  user:
    name: "{{ item.name }}"
    create_home: yes
    groups: surgers
  with_items: "{{ users }}"

- name: sudo without password for wheel group
  copy:
    content: '%surgers ALL=(ALL:ALL) NOPASSWD:ALL'
    dest: /etc/sudoers.d/surgers_nopasswd
    mode: 0440

- name: Create SSH Folders
  become: true
  file:
    path: /home/{{ item.name }}/.ssh
    owner: "{{ item.name }}"
    state: directory
  with_items: "{{ users }}"

- name: Set authorized key
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"
  with_items: "{{ users }}"
