---

- debug:
    var: ansible_distribution

- name: Disable Windows Defender for Windows 10
   win_shell: 'Set-MpPreference -DisableRealtimeMonitoring $true'
   when: ansible_distribution == "Microsoft Windows 10 Enterprise"

- name: Disable Windows Defender in Windows Server windows_domain_controller
  win_shell: 'Uninstall-WindowsFeature -Name Windows-Defender'
  when: ansible_distribution == "Microsoft Windows Server 2016 Datacenter" or
        ansible_distribution == "Microsoft Windows Server 2016 Standard Evaluation"
