---

- name: Copy add_users script to host
  win_copy:
    src: "disable_defender.ps1"
    dest: "C:\\disable_defender.ps1"
    
- name: Run disable defender script
  win_shell: "C:\\disable_defender.ps1"
  register: result
  
- name: Disable Real-Time Protection of Windows Defender for Windows 10
  ignore_errors: yes
  win_regedit:
    path: "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Real-Time Protection"
    name: DisableRealtimeMonitoring
    type: dword
    data: 1
